Polymer/tools

bin/pull-all-0.8.sh, repo-configs/0.8/elements.json
@cdata @notwaldorf @azakus @garlicnation PTAL
=> add config to pull PolymerElements

repo-configs/0.8/docs.json
=> Add docs.json, elements needed for doc generation

travis/README.md
=> Remove quotes from encrypt commands

packages/editor-service/package-lock.json, packages/editor-service/package.json, packages/editor-service/src/test/util.ts
Moved from https://github.com/Polymer/polymer-editor-service/pull/118
=> Update vscode languageserver

.travis.yml, packages/browser-capabilities/package-lock.json, packages/cli/npm-shrinkwrap.json, packages/cli/src/test/integration/build_test.ts, packages/cli/src/test/integration/integration_test.ts, packages/editor-service/package-lock.json, packages/polyserve/package-lock.json
Previous to this, our integration tests were only _actually_ running on appveyor, not on travis.
=> Fix travis definition of integration tests.

packages/editor-service/src/test/definition-finder_test.ts
See https://github.com/Polymer/tools/issues/170
=> Skip DefinitionFinder tests for the moment.

.travis.yml, appveyor.yml
Decrease travis utilization by 50%
=> Limit travis and appveyor to building master branch and PR commits only.

packages/cli/CHANGELOG.md, packages/cli/src/commands/build.ts
Fixes #175. Code changes previously reviewed (but unmerged) in https://github.com/Polymer/polymer-cli/pull/920
=> Add --auto-base-path flag to build

packages/cli/gulpfile.js, packages/cli/npm-shrinkwrap.json, packages/cli/package.json, packages/cli/src/github/github.ts, packages/cli/src/init/application/application.ts, packages/cli/src/init/element/element.ts, packages/cli/src/init/github.ts, packages/cli/src/test/integration/integration_test.ts, packages/cli/src/test/unit/github/github_test.ts, tools.code-workspace
=> Integration test: checkout and build 3.0 shop

.travis.yml, package.json, packages/cli/gulpfile.js
=> Run integration tests in parallel on travis.

.travis.yml, appveyor.yml
This is just the travis and appveyor configs limiting node v to 6 and 9.
=> Updated travis and appveyor configs to run node 9 instead of latest (aka 10)

.travis.yml
Because WCT/sauce is being flaky and making the build look sadder than it really is.
=> Split unit and integration test runs.

packages/cli/CHANGELOG.md, packages/polyserve/CHANGELOG.md, packages/polyserve/src/make_app.ts, packages/polyserve/src/start_server.ts, packages/web-component-tester/test/integration/browser.ts
Fixes https://github.com/Polymer/tools/issues/206
=> Disable cache headers that do not account for transforms.

packages/build/CHANGELOG.md, packages/build/src/custom-elements-es5-adapter.ts, packages/cli/CHANGELOG.md, packages/polyserve/CHANGELOG.md
=> Add webcomponents-bundle.js to ES5 injector regex.

packages/analyzer/src/javascript/function-scanner.ts
Minor issue, just want to have 100% green output.
=> Removed unused imports that were causing warnings on build

packages/build/src/babel-plugin-bare-specifiers.ts
=> Fix typo in import expression

packages/cli/src/test/integration/integration_test.ts, packages/web-component-tester/test/integration/browser.ts
https://github.com/Polymer/tools/issues/287
https://github.com/Polymer/tools/issues/289
=> Temporarily disable some broken tests

packages/analyzer/src/test/css/css-custom-property-scanner_test.ts, packages/analyzer/src/test/html/html-document_test.ts, packages/analyzer/src/test/html/html-script-scanner_test.ts, packages/analyzer/src/test/javascript/class-scanner_test.ts, packages/analyzer/src/test/javascript/function-scanner_test.ts, packages/analyzer/src/test/javascript/javascript-import-scanner_test.ts, packages/analyzer/src/test/javascript/namespace-scanner_test.ts, packages/analyzer/src/test/polymer/polymer-element_test.ts, packages/analyzer/src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts, packages/analyzer/src/test/polymer/polymer2-element-scanner_test.ts, packages/analyzer/src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts, packages/analyzer/src/test/polymer/polymer2-mixin-scanner_test.ts, packages/bundler/src/test/bundler_test.ts, packages/bundler/src/test/html-bundler_test.ts, packages/bundler/src/test/shards_test.ts
Except in WCT which is still using the BDD API.
=> Use the setup and teardown family of functions consistently

packages/cli/src/test/integration/integration_test.ts
Fixes https://github.com/Polymer/tools/issues/287
=> Re-enable 3.x element template init test.

packages/polyserve/CHANGELOG.md, packages/polyserve/src/compile-middleware.ts
=> fix issue with routes being substrings but not root path requests

packages/esm-amd-loader/test/src/suite.ts, packages/esm-amd-loader/test/static/race/bar.js, packages/esm-amd-loader/test/static/race/baz.js, packages/esm-amd-loader/test/static/race/foo.js, packages/esm-amd-loader/test/static/race/start.js
=> Add a test for https://github.com/Polymer/tools/issues/335, skipped for now.

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/templates/application/polymer-3.x/package.json, packages/cli/templates/application/polymer-3.x/src/_element/_element.js, packages/cli/templates/element/polymer-3.x/_element.js, packages/cli/templates/element/polymer-3.x/package.json
Fixes https://github.com/Polymer/tools/issues/357 and when we release, will reduce download size for users by 250mb.
=> [cli] Fixed polymer 3.x templates and updated CHANGELOG to prepare for CLI release.

packages/web-component-tester/CHANGELOG.md, packages/web-component-tester/package-lock.json, packages/web-component-tester/package.json
Tests and build are passing locally.
Resolves #227
=> [wct] Updated Mocha to the latest version and regenerated a lockfile.

packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/esm-amd-loader/test/package-lock.json, packages/linter/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-local/package-lock.json, packages/wct-sauce/.github/CODEOWNERS, packages/wct-sauce/.jshintrc, packages/wct-sauce/CHANGELOG.md, packages/wct-sauce/default-sauce-browsers.json, packages/wct-sauce/lib/browsers.js, packages/wct-sauce/lib/plugin.js, packages/wct-sauce/lib/sauce.js, packages/wct-sauce/lib/travis.js, packages/wct-sauce/package-lock.json, packages/wct-sauce/package.json, packages/wct-sauce/scripts/postinstall.js, packages/wct-sauce/travis-browsers.json, packages/web-component-tester/package-lock.json
I migrated a function from lib/sauce.js to lib/travis.js because of the way monorepo'd dependencies are processed, I needed the postinstall.js script to not `require()` any unnecessary npm dependencies; no external dependencies needed now.
=> Import wct-sauce into the monorepo

packages/build/README.md
I guess based on polymer 3 sample apps, they should be updated to .js.
=> Updating readme

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/polyserve/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-local/package-lock.json
=> Prepare CLI 1.7.3 release.

packages/project-config/CHANGELOG.md, packages/project-config/src/builds.ts
=> Add `modules` to the uncompiled build presets.

packages/modulizer/package.json
This script breaks fresh clone bootstrap.
=> Remove polymer-modulizer's prepare script.

packages/gen-typescript-declarations/README.md
=> [gen-typescript-declarations] README updates.

packages/web-component-tester/browser/childrunner.ts
=> Fix issue 229 part 1

package-lock.json, package.json, packages/web-component-tester/runner/config.ts
This seemed to just work with only one typings fix in one file.
🤯
=> Upgraded typescript to 3.0.1

package-lock.json, packages/analyzer/CHANGELOG.md, packages/analyzer/package-lock.json, packages/analyzer/package.json, packages/browser-capabilities/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/esm-amd-loader/test/package-lock.json, packages/gen-typescript-declarations/CHANGELOG.md, packages/gen-typescript-declarations/package-lock.json, packages/gen-typescript-declarations/package.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-local/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
=> Prepare release of gen-typescript-declarations and analyzer.

packages/browser-capabilities/src/browser-capabilities.ts
Fixes #640
Changes browserName of Opera in browserCapabilities.
=> [browserCapabilities] Corrected browserName for Opera

packages/browser-capabilities/CHANGELOG.md, packages/browser-capabilities/package.json, packages/browser-capabilities/src/test/browser-capabilities_test.ts
Also add CHANGELOG and test for #652
=> Release browser-capabilities.

packages/cli/src/test/integration/integration_test.ts
Was broken pending release of https://github.com/Polymer/polymer/pull/5300
=> Re-enable lint test

packages/browser-capabilities/README.md
The URL was pointing back to the old repo.
=> [browser-capabilities] Update README.md with correct URL

packages/bundler/CHANGELOG.md, packages/bundler/src/bin/polymer-bundler.ts
Fixes issue https://github.com/Polymer/tools/issues/741
=> Fixed issue with chalk templates breaking `polymer-bundler -h`

.travis.yml
wct-local is currently failing at driving Firefox 63.  Below is the stacktrace of the error.  This PR simply sets the version of Firefox installed on Travis to version 62 as a means to defer fixing the bug so we can keep tests infrastructure functioning.
```
org.openqa.selenium.WebDriverException: newSession
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'redacted.something.wat', ip: '192.168.128.55', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_112'
Driver info: driver.version: unknown
remote stacktrace: WebDriverError@chrome://marionette/content/error.js:178:5
UnknownCommandError@chrome://marionette/content/error.js:472:5
despatch@chrome://marionette/content/server.js:290:13 …
```
=> Pin firefox at version 62 for travis testing until we can get 63 working with wct-local/selenium-standalone

packages/browser-capabilities/package-lock.json, packages/build/package-lock.json, packages/modulizer/package-lock.json, packages/wct-mocha/CHANGELOG.md, packages/wct-mocha/package-lock.json, packages/wct-mocha/package.json
=> Prepare Release of wct-mocha@1.0.0-pre.3

packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/esm-amd-loader/test/package.json, packages/wct-browser-legacy/test/package.json, packages/wct-local/CHANGELOG.md, packages/wct-mocha/test/package.json, packages/web-component-tester/CHANGELOG.md, packages/web-component-tester/package-lock.json, packages/web-component-tester/package.json
=> Prepare releases of CLI (prerelease) and WCT (official release)

packages/cli/templates/application/polymer-3.x/package.json, packages/cli/templates/element/polymer-3.x/package.json
=> Updated wct-mocha to version 1.0.0 in the polymer 3.x templates in polymer-cli.

packages/gen-typescript-declarations/package.json
`@polymer/gen-typescript-declarations` update-goldens script makes sure fixtures in place first.
=> [@polymer/gen-typescript-declarations] Updated the update-goldens script

package-lock.json, packages/analyzer/package-lock.json, packages/browser-capabilities/CHANGELOG.md, packages/browser-capabilities/package-lock.json, packages/browser-capabilities/package.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
This PR exists because I didn't release browser-capabilities in last batch due to no CHANGELOG entries indicating updates.
=> Updated CHANGELOG and package files for release of browser-capabilities and polymer-cli.

package-lock.json, packages/analyzer/CHANGELOG.md, packages/analyzer/package-lock.json, packages/analyzer/package.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/package-lock.json, packages/cli/src/test/unit/commands/serve_test.ts, packages/cli/src/test/unit/init/init_test.ts, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/esm-amd-loader/test/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/polyserve/src/transform-middleware.ts, packages/project-config/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-browser-legacy/test/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/package-lock.json, packages/wct-mocha/test/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/web-component-tester/runner/config.ts, packages/web-component-tester/runner/context.ts, packages/workspaces/package-lock.json
=> Prepare analyzer 3.2.0 release.

packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/gen-typescript-declarations/CHANGELOG.md, packages/gen-typescript-declarations/package-lock.json, packages/gen-typescript-declarations/package.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/web-component-tester/package-lock.json
=> Prepare gen-typescript-declarations release 1.6.0

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/common/package-lock.json, packages/esm-amd-loader/CHANGELOG.md, packages/esm-amd-loader/package-lock.json, packages/esm-amd-loader/package.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/wct-mocha/package-lock.json, packages/web-component-tester/package-lock.json
=> Prepare esm-amd-loader 1.0.4 and cli 1.9.2 releases

packages/polyserve/src/cli.ts
Looks like just a one-off typo.
=> Fix compile-cache cli option not being respected.

package-lock.json, packages/analyzer/CHANGELOG.md, packages/analyzer/package-lock.json, packages/analyzer/package.json, packages/browser-capabilities/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/CHANGELOG.md, packages/modulizer/package-lock.json, packages/modulizer/package.json, packages/polyserve/CHANGELOG.md, packages/polyserve/package-lock.json, packages/polyserve/package.json, packages/project-config/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/package-lock.json, packages/web-component-tester/CHANGELOG.md, packages/web-component-tester/package-lock.json, packages/web-component-tester/package.json, packages/workspaces/package-lock.json
And separate from polymer-cli:
=> Prepare 1.9.3 cli + upstream deps release

packages/cli/CHANGELOG.md, packages/cli/src/args.ts
=> Add cli argument description for --version

packages/bundler/README.md
Too many bracket in README.md.
=> Remove an unnecessary bracket

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/bundler/CHANGELOG.md, packages/bundler/package-lock.json, packages/bundler/package.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/gen-typescript-declarations/CHANGELOG.md, packages/gen-typescript-declarations/package-lock.json, packages/gen-typescript-declarations/package.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-browser-legacy/test/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/test/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
=> Prepare release

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/esm-amd-loader/test/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-browser-legacy/test/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/package-lock.json, packages/wct-mocha/test/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
=> Prepare polymer-cli@1.9.6 release

packages/bundler/CHANGELOG.md, packages/bundler/package.json
=> Updated CHANGELOG and package.json for bundler 4.0.8 release.

packages/esm-amd-loader/test/run-wct.sh, packages/wct-browser-legacy/test/run-wct.sh, packages/wct-mocha/test/run-wct.sh
=> ci(): avoid using local browsers if flag  is set

packages/build/CHANGELOG.md, packages/build/src/bundle.ts, packages/bundler/CHANGELOG.md, packages/cli/CHANGELOG.md, packages/cli/test/fixtures/build-modules/expected/bundled-amd/shared_bundle_1.js, packages/cli/test/fixtures/build-modules/expected/bundled-es/shared_bundle_1.js, packages/cli/test/fixtures/build-modules/expected/bundled-inlined-es-treeshake/index.html, packages/cli/test/fixtures/build-modules/expected/bundled-inlined-es/index.html, packages/cli/test/fixtures/build-modules/expected/polymer.json, packages/cli/test/fixtures/build-modules/expected/unbundled-amd/mod1.js, packages/cli/test/fixtures/build-modules/expected/unbundled-es/mod1.js, packages/cli/test/fixtures/build-modules/source/mod1.js, packages/cli/test/fixtures/build-modules/source/polymer.json, packages/project-config/CHANGELOG.md, packages/project-config/src/builds.ts, packages/project-config/src/test/index_test.ts, packages/project-config/test/polymer-full.json
Adds support for `treeshake` option in Polymer Project Config, Build and CLI now that it's in Bundler.
=> Polymer treeshake

package-lock.json, packages/build/CHANGELOG.md, packages/build/package-lock.json, packages/build/package.json, packages/bundler/CHANGELOG.md, packages/bundler/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json
=> Prepare release of polymer-cli + polymer-build to fix minification for polymer 3.2.0

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/polyserve/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/CHANGELOG.md, packages/wct-mocha/package.json, packages/web-component-tester/package-lock.json
Not going to release CLI etc as part of this.  Am going to release this one first so I can update the CLI's polymer 3 templates to use mocha ^6 and wct-mocha ^1.0.1
=> wct-mocha 1.0.1 release

packages/wct-local/selenium-overrides.js
This should fix https://github.com/Polymer/tools/issues/405
=> Upgrade to selenium standalone server 3.141.59

package-lock.json, packages/analyzer/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/CHANGELOG.md, packages/cli/package-lock.json, packages/cli/package.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-local/CHANGELOG.md, packages/wct-local/package-lock.json, packages/wct-local/package.json, packages/wct-mocha/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
=> Prepare releases of wct-local and polymer-cli

package-lock.json, packages/analyzer/package-lock.json, packages/browser-capabilities/package-lock.json, packages/build/package-lock.json, packages/bundler/package-lock.json, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/help.ts, packages/cli/src/commands/lint.ts, packages/cli/src/init/application/application.ts, packages/cli/src/init/element/element.ts, packages/cli/src/init/init.ts, packages/cli/src/lint/lint.ts, packages/common/package-lock.json, packages/dom5/package-lock.json, packages/editor-service/package-lock.json, packages/esm-amd-loader/package-lock.json, packages/gen-typescript-declarations/package-lock.json, packages/linter/package-lock.json, packages/modulizer/package-lock.json, packages/polyserve/package-lock.json, packages/project-config/package-lock.json, packages/wct-browser-legacy/package-lock.json, packages/wct-browser-legacy/test/package-lock.json, packages/wct-local/package-lock.json, packages/wct-mocha/package-lock.json, packages/wct-mocha/test/package-lock.json, packages/wct-sauce/package-lock.json, packages/web-component-tester/package-lock.json, packages/workspaces/package-lock.json
Includes newer version of chalk and updated package-locks all-around.
Resolving conflicts in package-lock.json from #623 was not convenient without access to branch so this was most expedient way to update the library.
Thanks to @43081j
=> Updated chalk to latest version; implemented the updates from #623

packages/wct-local/custom_typings/selenium-standalone.d.ts, packages/wct-local/package.json, packages/wct-local/src/plugin.ts, packages/wct-local/src/selenium.ts
Bug: https://github.com/Polymer/web-component-tester/issues/676
=> Add support for selenium-java-args
