travis/sample-travis-with-sauce.yml
travis/sample-travis-without-sauce.yml

Since the Travis sample code will [most probably](https://www.youtube.com/watch?v=afy_EEq_4Go&t=4m26s) end up in repositories recognize on or after 2015-01-01, there is no need to include `sudo: false` as that is now the default.
---
From http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure:
> The default behavior, when no sudo usage is detected in any customizable build phases, depends on the date when the repository is first recognized by Travis CI:
>
>    * For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.
>    * __For repos we recognize on or after 2015-01-01, linux builds are sent to our container-based infrastructure__

Remove `sudo: false` from the sample Travis files?

---

packages/build/CHANGELOG.md
packages/build/package-lock.json
packages/build/src/js-transform.ts
packages/build/src/optimize-streams.ts
packages/build/src/test/js-transform_test.ts

Previously they never did. Added the `omitInlineHelpers` option to optionally disable inlining.
Addresses #987

jsTransform now inlines Babel helpers by default.

---

packages/cli/npm-shrinkwrap.json
packages/linter/package-lock.json
packages/linter/package.json
packages/polyserve/package-lock.json

Cross-package dependency versions need to match the current version exactly, or lerna won't create a symlink. This results in tsc finding typings from both the local node_modules folder, and the dependency package.
Passes locally. If it passes on CI I'll submit TBR.

Fix tests.

---

packages/cli/CHANGELOG.md

The previous release was published totally unbuilt. Entirely my mistake, it's because I'm so used to using np which automatically runs "build", while "lerna publish" does not.
Maybe we should just put "build" in our prepublish (should be prepack actually) scripts. Or just not use "lerna publish".

Prepare CLI 1.7.0-pre.8 release.

---

packages/linter/CHANGELOG.md

This is needed because the prior release of linter is pinned to an older version of analyzer, which means unless linked by lerna, the package will not build.

Prepare linter 3.0.0-pre.6 release.

---

packages/build/CHANGELOG.md
packages/build/src/html-transform.ts
packages/build/src/js-transform.ts
packages/build/src/path-transformers.ts
packages/build/src/test/babel-plugin-bare-specifiers_test.ts
packages/build/src/test/babel-plugin-import-meta_test.ts
packages/build/src/test/bundle_test.ts
packages/build/src/test/html-transform_test.ts
packages/build/src/test/optimize-streams_test.ts
packages/cli/CHANGELOG.md
packages/polyserve/CHANGELOG.md
packages/polyserve/test/bower_components/test-modules/golden/test-suite-no-wct.html
packages/polyserve/test/bower_components/test-modules/golden/test-suite-wct.html

Fix AMD transform bug where if an HTML document had multiple type=module
scripts, and any of them (apart from the first) had any kind of import,
then that import was not accessible (because it was mapped to the wrong
module callback function argument).
Fixes #112

Fix wrong AMD transform dependency/callback parameter ordering.

---

package.json
packages/linter/package.json

This test doesn't run locally (out of memory), and I am told does not
actually perform any testing anyway.

Disable the linter integration test.

---

packages/linter/src/collections.ts

Currently it is just a clone of the polymer-2 recommended rules.
Fixes https://github.com/Polymer/tools/issues/130

Add a polymer-3 linter collection.

---

packages/cli/src/test/integration/integration_test.ts
packages/cli/templates/element/polymer-3.x/polymer.json

This was specifically excluded [in #115](https://github.com/Polymer/tools/pull/115/files#diff-10eed550dca082f37ae2a959b6f87823R49) because `polymer lint` did not have a set of rules for Polymer 3 at the time.

Add `polymer lint` to the Polymer 3 element template integration test.

---

packages/cli/src/commands/test.ts
packages/cli/src/test/integration/integration_test.ts
packages/cli/src/test/unit/commands/test_test.ts

[cli] `test`: Pass `moduleResolution` option from config to WCT.

---

packages/build/gulpfile.js

gulp dependencies run in parallel, so this recent change broke the test script.

Fix broken test:unit gulp task.

---

packages/editor-service/src/test/auto-completer_test.ts

Skip the AutoCompleter suite for the moment due to flaky tests.

---

packages/build/src/test/js-transform_test.ts
packages/build/src/test/util.ts

I noticed when trying out #171 that `build` emits a super scary looking stack trace as part of its expected output when testing. This captures and asserts on that output instead.

Capture and assert on error output.

---

packages/build/CHANGELOG.md
packages/build/src/js-transform.ts
packages/build/src/test/js-transform_test.ts
packages/cli/CHANGELOG.md
packages/polyserve/CHANGELOG.md

Disable Babel `minify-constant-folding` plugin when minifying. This
plugin has a bug that breaks when a constant is exported from a module
(https://github.com/babel/minify/issues/820).
Fixes https://github.com/Polymer/polymer-cli/issues/998

Disable minify-constant-folding plugin.

---

packages/browser-capabilities/src/browser-capabilities.ts

Versions 11.1 for desktop and 11.3 for iOS now support Service Workers as per https://caniuse.com/#search=serviceworkers. Verified locally with Xcode Simulator and desktop running macOS 10.13.4.

Safari now supports Service Workers

---

lerna.json

Also only allow publishing from master.
Reference: https://github.com/lerna/lerna#lernajson and https://github.com/lerna/lerna#--allow-branch-glob
(not convinced this is working yet)

Ignore certain files when deciding what needs an update.

---

.travis.yml
package.json
packages/browser-capabilities/test/mocha.opts
packages/build/gulpfile.js
packages/cli/gulpfile.js
packages/editor-service/test/mocha.opts
packages/linter/test/mocha.opts
packages/polyserve/test/mocha.opts
packages/web-component-tester/gulpfile.js

Before...
After merging...
There's about a 2min real-time *increase* but a 10min resource-time *decrease* to doing it this way.  Not clear if it's a win to make CI runs +10% longer to go green best-case scenario for a -30% resource-time reduction.  If travis resource utilization is high, waiting for VMs can add significantly more time (I've waited an hour before) than the extra 2min on an individual VM test run.

Run all tests in parallel on same vm

---

packages/analyzer/custom_typings/stable.d.ts
packages/analyzer/src/model/warning.ts

This was causing warnings to emit on build.  Just getting rid of that.

Added custom typings for the inplace method of stable.d.ts to avoid implicit any warnings.

---

packages/bundler/src/es6-rewriter.ts
packages/bundler/src/test/es6-module-bundling-scenarios_test.ts

There were a few of things that were fixed here.
One small one is, bundler excludes were resulting in rollup errors when imports/exports referenced them.  That was quickly addressed with https://github.com/Polymer/tools/compare/wtf-file-urls?expand=1#diff-87a72e027be8b635fde7aca6c20d749bR52 and that was found and covered now because I used an `excludes` setting in a test to prove the behavior of the focus of the PR, which is...
Second fix is that export sources are rewritten to the bundle URL or otherwise correct relative URL.
Third fix was forgetting to ensure leading dot for relative URL in the import from non-bundled URL case.

Rewrite the source value of export declarations so we do not emit file URLs in our output.

---

.travis.yml

Made this so only one integration server run does the sauces so we have 50% less contention for sauce sessions which means more test-passing goodness.

Get integration tests happy again

---

packages/analyzer/src/javascript/class-scanner.ts
packages/analyzer/src/javascript/esutil.ts
packages/analyzer/src/javascript/function-scanner.ts
packages/analyzer/src/test/css/css-custom-property-scanner_test.ts
packages/analyzer/src/test/html/html-document_test.ts
packages/analyzer/src/test/html/html-script-scanner_test.ts
packages/analyzer/src/test/javascript/class-scanner_test.ts
packages/analyzer/src/test/javascript/function-scanner_test.ts
packages/analyzer/src/test/javascript/javascript-import-scanner_test.ts
packages/analyzer/src/test/javascript/namespace-scanner_test.ts
packages/analyzer/src/test/javascript/resolve-specifier-node_test.ts
packages/analyzer/src/test/polymer/polymer-element_test.ts
packages/analyzer/src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
packages/analyzer/src/test/polymer/polymer2-element-scanner_test.ts
packages/analyzer/src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
packages/analyzer/src/test/polymer/polymer2-mixin-scanner_test.ts
packages/analyzer/src/test/static/analysis/namespaces/analysis.json
packages/analyzer/src/test/static/namespaces/memberof-functions.js

They're public and interesting, same as functions on namespaces.
Also use getBestComment in more places, rather than our more ad hoc methods.
This also changes function source ranges a bit, but not in an interesting way IMO.
Part of Polymer/docs#2379

Scan exported functions

---

packages/analyzer/src/javascript/esutil.ts
packages/analyzer/src/polymer/behavior-scanner.ts
packages/build/src/html-splitter.ts
packages/build/src/service-worker.ts
packages/bundler/src/bundle-manifest.ts
packages/project-config/src/index.ts

As of node 10, `console.assert()` doesn't throw an AssertionError anymore.  However `const assert = require('assert'); assert();` does.  So I switched over to `assert()` wherever `console.assert()` was in use.

Replace all instances of `console.assert()` with `assert()` from 'assert' standard lib.

---

packages/cli/src/args.ts
packages/cli/src/commands/analyze.ts
packages/cli/src/commands/build.ts
packages/cli/src/commands/command.ts
packages/cli/src/commands/help.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/install.ts
packages/cli/src/commands/lint.ts
packages/cli/src/commands/serve.ts
packages/cli/src/commands/test.ts
packages/cli/src/lint/lint.ts
packages/cli/src/polymer-cli.ts
packages/cli/src/run.ts
packages/cli/src/test/unit/commands/serve_test.ts
packages/cli/src/test/unit/commands/test_test.ts
packages/cli/src/util.ts

~3x speedup of `polymer --help` from 2.25s  to 0.75s, mostly because of a strict import of polymer-build that crept in.

Speedup polymer cli init with lazy imports.

---

packages/cli/README.md

`polymer install` now installs from npm if you provide the `--npm` flag or add the `npm` setting in your `polymer.json`.
https://github.com/Polymer/tools/blob/0cdecd03e7e3709f84fa4f5a52443c19988112be/packages/cli/src/install/install.ts#L50-L53
Fixes #197.

Update the CLI README.md to include info about `polymer install --npm`.

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/html/html-script-scanner.ts
packages/analyzer/src/html/html-script-tag.ts
packages/analyzer/src/test/core/analyzer_test.ts
packages/analyzer/src/test/static/script-tags/modules/index.html
packages/analyzer/src/test/static/script-tags/modules/usesClass.js

They opt out of our funky reverse-import-and-artificial-document hack we did for non-module scripts.
Also add `ScriptTagImport#isModule`.
This also fixes an issue in generating analysis.json for webcomponents.org

Module script tag imports are normal imports.

---

packages/cli/src/test/integration/integration_test.ts

Will fail until https://github.com/Polymer/tools/pull/307 is merged

Add an integration test of our import.meta support.

---

packages/build/src/optimize-streams.ts

Only inject regenerator with ES5, and Babel helpers with <= ES2017

---

packages/build/src/babel-plugin-bare-specifiers.ts
packages/cli/src/github/github.ts
packages/cli/src/init/github.ts
packages/cli/src/test/integration/integration_test.ts

Adds tests of the source with a few different polyserve definitions.
Also breaks out each of the individual build configuration tests.
This isn't bad performance-wise, because the vast majority of the cost is in `npm install` and `polymer build` which is not repeated.
Also removes some unnecessary and distracting logging statements.

Break out more shop tests.

---

packages/build/CHANGELOG.md
packages/cli/CHANGELOG.md
packages/project-config/CHANGELOG.md

These were forgotten earlier, but are pretty important.

Add CHANGELOG entries for new compile target options.

---

packages/bundler/src/es6-module-utils.ts
packages/bundler/src/es6-rewriter.ts
packages/bundler/src/test/import-meta-url_test.ts
packages/bundler/src/utils.ts

- Removed an obsolete TODO about `export * from` which was previously fixed. 5fa64a1
- Use the already defined assertJsDocument() and avoid unnecessary cast. 7e9f6a5
- Generate unique identifier name for the bundledImportMeta stand-in variable for bundled import.meta transform. 6b907ae

[bundler] Tie up a few small loose ends in bundler code

---

packages/bundler/package-lock.json
packages/bundler/package.json

These typings are now being shipped by Rollup itself: https://www.npmjs.com/package/@types/rollup
My `npm install` reordered some fields in the `package.json`. I assume this is new npm behavior :thinking: The content is still the same though. (For example `license` was duplicate specified)

Remove @types/rollup from bundler

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/core/analysis-cache.ts
packages/analyzer/src/core/analysis-context.ts
packages/analyzer/src/core/analyzer.ts
packages/analyzer/src/model/import.ts
packages/analyzer/src/test/core/analyzer_test.ts
packages/analyzer/src/test/html/html-script-scanner_test.ts
packages/analyzer/src/test/test-utils.ts
packages/analyzer/src/url-loader/fs-url-loader.ts
packages/editor-service/src/test/diagnostics_test.ts

Previously, there were many places for error messages to get lost, in part because we weren't tracking errors in the type system. This moves all expected errors in AnalysisContext into the type system with the Result type.

Handle errors early in analysis better.

---

.travis.yml

Simplify Travis config by using "include" to set the matrix directly.
Also scopes browser installation and xvfb to only those builds that need it.

Simplify Travis build matrix.

---

README.md

Remove 'WIP' from the monorepo README because, c'mon.

---

packages/project-config/src/builds.ts

Correct the names of the new uncompiled presets as build names must be unique

Correct the names of the new uncompiled presets

---

packages/analyzer/package-lock.json
packages/browser-capabilities/package-lock.json
packages/build/CHANGELOG.md
packages/build/package-lock.json
packages/build/package.json
packages/bundler/package-lock.json
packages/cli/package-lock.json
packages/common/package-lock.json
packages/editor-service/package-lock.json
packages/esm-amd-loader/package-lock.json
packages/esm-amd-loader/test/package-lock.json
packages/linter/package-lock.json
packages/polyserve/package-lock.json
packages/project-config/package-lock.json
packages/web-component-tester/package-lock.json

Latest version of this package `babel-plugin-minify-guarded-expressions` which is a dependency of `babel-preset-minify@0.4.0-alpha.caaefb4c` we have pinned will throw errors due to trying to get a parentPath from a path's parentPath in some cases where one does not exist and kills the entire optimize-streams.ts transform.

[build] Pin babel-plugin-minify-guarded-expressions to 0.4.1

---

packages/build/CHANGELOG.md
packages/build/package.json
packages/cli/package.json

- pin dep for babel-preset-minify's minify-guarded-exceptions plugin because of errors)
- Fix bug in polymer-3-element init template where polymer/dom-module.js
could be loaded twice when serving from the polyserve /components/
directory.
- Fix names of uncompiled-bundled and uncompiled-unbundled build presets.

Release [cli] 1.7.2 and [build] 3.0.1

---

packages/web-component-tester/wct-browser-legacy/CHANGELOG.md
packages/web-component-tester/wct-browser-legacy/package-lock.json
packages/web-component-tester/wct-browser-legacy/package.json

**This is a RELEASE PR for wct-browser-legacy 1.0.1**
Addressing an oversight that it should have been released with `@webcomponents/webcomponentsjs` v2 already.

[wct-browser-legacy] Updated `@webcomponents/webcomponentsjs` dependency to ^2.0.0 from ^1.0.7

---

.travis.yml
packages/esm-amd-loader/test/package.json
packages/esm-amd-loader/test/run-wct.sh
packages/esm-amd-loader/test/wct.conf.json
packages/web-component-tester/test/integration/browser.ts

Also replace SKIP_REMOTE_BROWSERS env var with WCT_SAUCE.

Run esm-amd-loader on Sauce when configured.

---

.travis.yml
packages/esm-amd-loader/test/run-wct.sh
packages/web-component-tester/test/integration/browser.ts

We can't because secure environment variables aren't available. This was already happening before https://github.com/Polymer/tools/pull/441 but in a slightly different way. Without this change, community PRs will always fail on Travis.

Don't try to run Sauce from forked/community PRs.

---

packages/esm-amd-loader/CHANGELOG.md
packages/esm-amd-loader/package.json

Prepare esm-amd-loader 1.0.1 release.

---

packages/web-component-tester/README.md

Fixes a link to _browser/config.ts_ in **web-component-tester** _README_
resolves issue: ???  (I thought I made an issue but I don't see it anymore?)

fix link in README

---

packages/esm-amd-loader/src/esm-amd-loader.ts
packages/esm-amd-loader/test/src/suite.ts

Previously this test used a 1 second timeout to wait to see how many times the error callback was called, which was flaky on CI. Now we capture 404 errors and check callback calls after two 404s.
Fixes #507
(Note first commit is just clang formatting).

Make esm-amd-loader dynamic require 404 test not flaky.

---

packages/web-component-tester/bin/wct
packages/web-component-tester/bin/wct-st
packages/web-component-tester/runner/cli.ts

Also remove promise in wct-st, as the promise resolves immediately on
sauce tunnel creation, killing the new sauce tunnel
Fixes #438

Remove unused callback argument to wct.cli.run and wct.cli.startSauceTunnel

---

packages/web-component-tester/CHANGELOG.md
packages/web-component-tester/README.md
packages/web-component-tester/runner/config.ts

Supersedes https://github.com/Polymer/web-component-tester/pull/698
Fixes #416 https://github.com/Polymer/polymer-cli/issues/919 https://github.com/Polymer/web-component-tester/issues/652 
@usergenic

Fix: WCT CLI arg standardizing

---

.travis.yml
appveyor.yml
packages/build/CHANGELOG.md
packages/build/src/base-tag-updater.ts
packages/build/src/bundle.ts
packages/build/src/custom-elements-es5-adapter.ts
packages/build/src/html-splitter.ts
packages/build/src/inject-babel-helpers.ts
packages/build/src/optimize-streams.ts
packages/build/src/prefetch-links.ts
packages/build/src/push-manifest.ts
packages/build/src/service-worker.ts
packages/build/src/test/bundle_test.ts
packages/build/src/test/html-splitter_test.ts
packages/cli/test/fixtures/build-with-preset/expected/es5-bundled/service-worker.js
packages/polyserve/src/transform-middleware.ts

- Run tests on Node 10 instead of 9. (10.5+ supported; 10.4.x and under have a broken `fs.chmod()` that doesn't play nice with the way we use Gulp.)
- generateServiceWorker relies on `Function.prototype.toString()` to insert function source code into the template to produce `service-worker.js`.  In Node 10, anonymous functions are emitted without the space between `function` keyword and the parentheses, whereas previously there was a space.  Now the generator replaces `/bfunction\(/` with `function (` explicitly so that behavior is consistent (and also integration tests based on static fixtures work for both versions).
- Converted `new Buffer(` calls to `Buffer.from(` as constructor deprecated in Node 10.
- `/test/fixtures/build-with-preset/expected/es5-bundled/service-worker.js` test …

Update tools to support Node 10

---

packages/analyzer/src/javascript/resolve-specifier-node.ts
packages/analyzer/src/test/javascript/resolve-specifier-node_test.ts
packages/analyzer/src/test/static/javascript/resolve-specifier-node/bower_components/bower_dep/package.json

The resolve module only resolves modules from the node_modules directory. Adding bower_components to it let's us use modules with bower, and matches the behavior of tools like Typescript.
Fixes https://github.com/Polymer/tools/issues/521

Add bower_components to list of module directories

---

packages/common/package-lock.json
packages/common/package.json

```bash
npx lerna exec --stream --scope @polymer/tools-common -- npm audit
```

Fix audit warnings in common

---

packages/polyserve/package-lock.json

```bash
npx lerna exec --stream --scope polyserve -- npm audit
```
**Note: This PR audit fails, as the latest version of polymer-bundler is not released yet.**
In https://github.com/Polymer/tools/commit/28403ca7d838dde3960fcd62063565c209a67c7d#diff-c7860144f1c9fb836793e097691c5a56 the vulnerable package `command-line-args` was updated, but it was not included in the latest release (https://github.com/Polymer/tools/commit/4d137fd44fdf3054c7ab6eed63e46a683656bc1e). Therefore, running the above command results in 1 vulnerability. Releasing a new version of `polymer-bundler` will resolve that.

Fix audit warnings in polyserve

---

packages/bundler/package-lock.json

```bash
npx lerna exec --stream --scope polymer-bundler -- npm audit
```

Fix audit warnings for polymer-bundler

---

packages/editor-service/package-lock.json

```bash
npx lerna exec --stream --scope polymer-editor-service -- npm audit
```

Fix audit warnings in editor-service

---

packages/analyzer/package-lock.json

```bash
npx lerna exec --stream --scope polymer-analyzer -- npm audit
```

Fix audit warnings in analyzer

---

packages/linter/package-lock.json

```bash
npx lerna exec --stream --scope polymer-linter -- npm audit
```

Fix audit warnings in linter

---

packages/project-config/package-lock.json

```bash
npx lerna exec --stream --scope polymer-project-config -- npm audit
```

Fix audit warnings in project-config

---

packages/wct-local/package-lock.json

```bash
npx lerna exec --stream --scope wct-local -- npm audit
```

Fix audit warnings in wct-local

---

packages/dom5/package-lock.json
packages/dom5/package.json

```bash
npx lerna exec --stream --scope dom5 -- npm audit
```

Fix audit warnings in dom5

---

packages/build/package-lock.json
packages/build/package.json
packages/build/src/test/optimize-streams_test.ts

```bash
npx lerna exec --stream --scope polymer-build -- npm audit
```
**Note: This PR audit fails, as the latest version of polymer-bundler is not released yet.**
In https://github.com/Polymer/tools/commit/28403ca7d838dde3960fcd62063565c209a67c7d#diff-c7860144f1c9fb836793e097691c5a56 the vulnerable package `command-line-args` was updated, but it was not included in the latest release (https://github.com/Polymer/tools/commit/4d137fd44fdf3054c7ab6eed63e46a683656bc1e). Therefore, running the above command results in 1 vulnerability. Releasing a new version of `polymer-bundler` will resolve that.

Fix audit warnings in build

---

packages/browser-capabilities/CHANGELOG.md
packages/browser-capabilities/src/browser-capabilities.ts
packages/browser-capabilities/src/test/browser-capabilities_test.ts

Treat Safari on iOS as though it were Safari Mobile. Also use iOS version, instead of Safari version, to better handle Safari Mobile.

Add browser-capabilities entry for Chrome on iOS.

---

packages/build/src/html-transform.ts
packages/build/src/js-transform.ts
packages/build/src/optimize-streams.ts

This option is no longer used because we order dependencies at runtime using our AMD loader instead.

Remove moduleScriptIdx option from JsTransformOptions.

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/model/reference.ts
packages/analyzer/src/test/model/reference_test.ts
packages/analyzer/src/test/static/javascript/exported-class.js

Resolves what `foo` is in `export {foo as bar}`.

[analyzer] Resolve `as` style module exports

---

packages/esm-amd-loader/CHANGELOG.md
packages/esm-amd-loader/README.md
packages/esm-amd-loader/package.json

Looks like some recent updates in our babel minify dependencies changed our minified output very slightly.
This caused the polyserve test I was running as part of its release in https://github.com/Polymer/tools/pull/558 to fail, since we have a brittle test there that relies on the exact contents. We should make that test less brittle, but in the meantime I'm just going to release the loader first.
Also update the documented size (which is actually due to a recent PR, not the minification change).

Prepare esm-amd-loader 1.0.2

---

packages/build/tsconfig.json
packages/linter/tsconfig.json

After an `npm run nuke` and `npm run build` I was getting errors in `polymer-linter` and `polymer-build` about the line in `@types/ua-parser-js` re-declaring an identifier `exported` in the line `export = exported` and it turns out there's a fix for this we had to do in `polyserve` to counter the same problem.  This fix should probably be globally applied in the `tsconfig-base.json` but that turns out to be problematic because of the way paths are calculated and inherited, so for now we'll have this particular patch in 3 places, up until the point they are no longer needed at all, we figure out how to do it in the base config, or we need to add it to yet-another tsconfig.

Update build and linter tsconfig.json because ua-parser-js issues.

---

packages/cli/templates/application/polymer-3.x/index.html

Purpose: Add crossorigin into scritp type=module tag inside  polymer-cli application template polymer-3.x to address issue with cli not working out of the box in Google Cloud Shell.
Reason: Lately, I've been doing some web dev on my chromebook and have been using Google Cloud Shell and Google Cloud Shell editor a lot. Whenever I've used polymer-cli to generate a project, I've had to make the above change to get it to work in the Web Previewer in Google Cloud Shell. I figured by throwing out a PR  I could save someone else a little bit of time.
I noticed a similar PR [here](https://github.com/Polymer/pwa-starter-kit/pull/105) with the associated issue and discussion [here](https://github.com/Polymer/pwa-starter-kit/issues/89). I assume that the same points about this not being a security …

Polymer-Cli  && Google Cloud Shell

---

packages/cli/CHANGELOG.md
packages/cli/src/build/build.ts

Hi,
According to [JsOptimizeOptions](https://github.com/Polymer/tools/blob/47bcbb1fe08300607c4b445394f385507c08fe67/packages/build/src/optimize-streams.ts#L56-L61), [JsCompileOptions](https://github.com/Polymer/tools/blob/47bcbb1fe08300607c4b445394f385507c08fe67/packages/build/src/optimize-streams.ts#L51-L54) and [JsCompileTarget](https://github.com/Polymer/tools/blob/840c7c86636153438c4b414869169aa38a6d07c6/packages/project-config/src/builds.ts#L17), the polymer-cli should add the CustomElementsEs5Adapter when a build has a **js.compile.target** equals to **es5**.
By example:
```json
"builds": [
{
"js": {
"minify": {
"exclude": [
"bower_components/fullcalendar/dist/fullcalendar.min.js",
"bower_components/jquery/dist/jquery.min.js",
"bower_components/moment/min/moment.min.js"
]
}, …
```

[cli] Add the CustomElementsEs5Adapter when options.js.compile.target equals es5

---

packages/gen-typescript-declarations/scripts/fixtures.txt

This issue came up when using `lit-element` and using `a11ySuite` in the WCT test suite.

Polymer dom flush only if polymer exists

---

packages/web-component-tester/data/a11ySuite.js

From https://github.com/Polymer/tools/pull/611.  This PR is just to ensure passing tests on latest rebase.
Looks like we essentially do the same in https://github.com/Polymer/tools/blob/master/packages/web-component-tester/browser/environment/helpers.ts#L128 but more so...
```ts
let scope;
if (window.Polymer && window.Polymer.dom && window.Polymer.dom.flush) {
scope = window.Polymer.dom;
} else if (window.Polymer && window.Polymer.flush) {
scope = window.Polymer;
} else if (window.WebComponents && window.WebComponents.flush) {
scope = window.WebComponents;
}
if (scope) {
scope.flush();
}
```
I won't amend a11ysuite.js to do that yet, but it is worth noting.

`Polymer.dom.flush()` only if `Polymer` exists

---

packages/gen-typescript-declarations/CHANGELOG.md
packages/gen-typescript-declarations/package-lock.json
packages/gen-typescript-declarations/package.json
packages/gen-typescript-declarations/src/cli.ts
packages/gen-typescript-declarations/src/verify.ts

Runs the generated typings through the TypeScript compiler (3.0) and fails with its error log if it fails.
The goal is to make integrating fully tested type generation into new repos (the Polymer elements) as trivial as possible.
cc https://github.com/Polymer/gen-typescript-declarations/issues/79 @43081j

[gen-typescript-declarations] Add --verify command-line flag.

---

packages/gen-typescript-declarations/CHANGELOG.md
packages/gen-typescript-declarations/src/cli.ts

We already did this for `addReferences`; same idea. These files are usually hand-written, so we don't want to delete them.

[gen-typescript-declarations] Don't delete files used by autoImport.

---

packages/gen-typescript-declarations/CHANGELOG.md
packages/gen-typescript-declarations/src/gen-ts.ts

This wasn't actually needed, and is wrong. Keeping the test though, which shows it already worked.

Revert autoImport for params fix from #636.

---

packages/gen-typescript-declarations/CHANGELOG.md
packages/gen-typescript-declarations/scripts/setup-fixtures.sh
packages/gen-typescript-declarations/src/gen-ts.ts

This time we ignore errors in files we don't care about (tests/demos).
Also, look for bower.json instead of package.json during test setup. Bower projects typically also have package.jsons, but not vice-versa, so this eliminates a bunch of warnings we had due to incorrect file
resolution in tests.

[gen-typescript-declarations] Error on analyzer errors, but only important files.

---

packages/gen-typescript-declarations/scripts/setup-fixtures.sh

Previously, the type generator test setup script would simply skip setting up a fixture directory if the directory already existed.
We now will only skip installing a fixture if both 1) the previous clone/install attempt actually succeeded (by touching an `INSTALL` file after npm/bower install), and 2) that the SHA for the fixture hasn't changed since the last install.
This should fix confusing local test breakages we sometimes hit, since previously you had to just know to delete the test fixtures sometimes.

More robust gen-tsd test fixture setup.

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/model/reference.ts
packages/gen-typescript-declarations/scripts/fixtures.txt
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/legacy/class.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/legacy/polymer.dom.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/mixins/property-effects.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/boot.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/flattened-nodes-observer.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/flush.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/render-status.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/settings.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/style-gather.d.ts
packages/gen-typescript-declarations/src/test/goldens/polymer-3/lib/utils/unresolved.d.ts

- Warn instead of throw when exported identifier is not resolved. Fixes https://github.com/Polymer/polymer-analyzer/issues/919
- Update type generator fixture SHA for Polymer (this latest SHA was failing before the Analyzer change in this PR).
- Prepare release of Analyzer 3.1.2

[analyzer] Warn instead of throw when exported identifier is not resolved.

---

packages/gen-typescript-declarations/CHANGELOG.md
packages/gen-typescript-declarations/package.json
packages/gen-typescript-declarations/src/gen-ts.ts
packages/gen-typescript-declarations/src/test/goldens/paper-button-3/paper-button.d.ts
packages/gen-typescript-declarations/src/test/goldens/paper-menu-button-3/paper-menu-button-animations.d.ts

Kind of an important omission I just noticed. Users should be able to import the interface we generate for legacy Polymer elements, even though those element definitions are not themselves exported.
Also prepare 1.5.1 for release.
cc @bicknellr I just verified that all types are still compiling after this change. Once it's released, refreshing all the package-lock.json files is all that's needed to pull in this fix.

Export generated legacy Polymer function element interfaces.

---

package.json

The old nuke script runs `npm install` before the bootstrap which is problematic when you have a package that isn't yet published, for example.  Also, this is not what lerna bootstrap package-locks are supposed to look like, so I wanted to avoid it doing this.  However, the `npm install` step was added by @TimvdLippe previously because the `npm audit` command would fail when hitting a package without a package-lock, which occurs in bootstrapped packages that have zero dependencies, in our case, that's `cleankill`.  So to solve the missing package-lock problem I just run `npm install --package-lock-only` on any package that doesn't have one, after the bootstrap.
This solved a recurring pain-point of being able to nuke/update the `wct-mocha-extraction` branch I'm working on which has …

Friendlier nuke script

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/html/html-document.ts

- Clone only the HTMLDocument ast, and stringify inline documents into the
cloned ast at the same position.
Fixes #688

Faster HTML Stringify

---

packages/cli/src/github/github.ts
packages/cli/src/init/github.ts
packages/cli/src/test/integration/integration_test.ts

Monorepo integration tests were broken because Polymer/shop 3.0 branch was deleted yesterday.
I had to add a new getTag method to the GitHub class to download a tag commit for the integration tests since we didn't have that scenario before.
Otherwise its same.

Updated polymer-cli integration tests to use v3.0.0 tag in Polymer/shop now that 3.0 branch has been deleted

---

packages/wct-local/CHANGELOG.md
packages/wct-local/scripts/postinstall.js

Ported over the two lines from https://github.com/Polymer/wct-local/pull/79

[wct-local] Added support for SELENIUM_OVERRIDES_CONFIG variable on postinstall.

---

packages/web-component-tester/runner/config.ts
packages/web-component-tester/runner/webserver.ts

I forgot to inject mocha into the scripts to load and that's totally necessary or generated index or `wct-mocha/browser.js` will complain that Mocha isn't loaded.
Also, I removed the definition of a default `wctPackageName` option in `config.ts` since `webserver.ts` now assigns (if undefined) in terms of the first resolved WCT client package when attempting to resolve them in order of wct-mocha, wct-browser-legacy, web-component-tester.

[web-component-tester] runner always needs to inject mocha for the generated index

---

packages/build/CHANGELOG.md
packages/build/src/html-transform.ts

For WCT to work properly with the esm-amd-loader, polymer-build adds a little hack where it waits for all defined modules to resolve before calling the original WCT waitFor callback.  That hack is only added when there is a recognized WCT client-side package.  Previously `web-component-tester/browser.js` or `wct-browser-legacy/browser.js`.  This PR just adds `wct-mocha/browser.js` to that list.

[polymer-build] Added wct-mocha to the list of supported WCT client-side packages in the html-transform.

---

package.json
packages/analyzer/package.json
packages/analyzer/tslint.json
packages/browser-capabilities/package.json
packages/build/tslint.json
packages/bundler/package.json
packages/bundler/tslint.json
packages/cleankill/index.ts
packages/cleankill/package.json
packages/cleankill/tslint.json
packages/cli/package.json
packages/cli/tslint.json
packages/dom5/tslint.json
packages/editor-service/package.json
packages/editor-service/tslint.json
packages/esm-amd-loader/package.json
packages/esm-amd-loader/test/package.json
packages/esm-amd-loader/tslint.json
packages/gen-typescript-declarations/package.json
packages/linter/package.json
packages/linter/tslint.json
packages/modulizer/package.json
packages/polyserve/package.json
packages/polyserve/tslint.json
packages/project-config/package.json
packages/project-config/src/test/builds_test.ts
packages/wct-local/package.json
packages/workspaces/package.json
packages/workspaces/tslint.json

Fixes #305.
---
Let me know if you still want this, otherwise i will throw it away.
* Added missing lint commands
* Made all tslint configs inherit the base one
* Fixed a couple of lint errors
* Added a lint script (`npm run lint`) to lint all packages
Couple of packages break the `no-any` rule so i turned it off as i didn't want to be altering interfaces for this.

all: standardise tslint config

---

packages/web-component-tester/runner/config.ts
packages/web-component-tester/runner/webserver.ts

Putting this into WCT ahead of the wct-mocha release so we can start testing with version of CLI we are releasing shortly.

Updated web-component-tester to support wct-mocha/wct-mocha.js instead of wct-mocha/browser.js

---

packages/bundler/CHANGELOG.md
packages/bundler/package.json

This is a patch release to fix the broken polymer-bundler CLI `-h` option (was due to breaking change in chalk brought in by command-line-usage package.

Updated bundler CHANGELOG and patch version number for release.

---

packages/wct-mocha/CHANGELOG.md
packages/wct-mocha/package.json
packages/wct-mocha/test/package.json

A version of wct-mocha 1.0.0-pre.1 was accidentally published as "latest" (and then unpublished) a month or so ago, which consumed the 1.0.0-pre.1 version, so this will be published as 1.0.0-pre.2

Updated version and CHANGELOG for prerelease of wct-mocha

---

packages/browser-capabilities/src/browser-capabilities.ts

Verified with https://20170915t110514-dot-polymer-shop.appspot.com/, the last version of Shop pushed with an older version of browser-capabilities that pushed to Firefox. Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1409570

Firefox push fixed in 63

---

packages/build/CHANGELOG.md
packages/build/src/js-transform.ts
packages/build/src/test/js-transform_test.ts

Fix issue https://github.com/Polymer/tools/issues/724 where deadcode removal in babel-minify can be error prone and result in removal of code which should not be removed and cause hard to debug errors.

Disable deadcode removal in babel-minify

---

packages/analyzer/src/core/analysis-context.ts

This is a quick and dirty fix for https://github.com/Polymer/tools/issues/736.

Recognize .mjs as JavaScript files

---

appveyor.yml
package-lock.json
packages/analyzer/package-lock.json
packages/build/package-lock.json
packages/bundler/package-lock.json
packages/cli/package-lock.json
packages/common/package-lock.json
packages/dom5/package-lock.json
packages/editor-service/package-lock.json
packages/editor-service/src/test/util.ts
packages/gen-typescript-declarations/package-lock.json
packages/linter/package-lock.json
packages/modulizer/package-lock.json
packages/polyserve/package-lock.json
packages/project-config/package-lock.json
packages/wct-browser-legacy/package-lock.json
packages/wct-local/package-lock.json
packages/wct-mocha/package-lock.json
packages/wct-sauce/package-lock.json
packages/web-component-tester/package-lock.json
packages/workspaces/package-lock.json

This seems to make builds go again after `npm run nuke` at least. Let's see if the tests pass...

Fix typings in editor-service tests to make tools build again

---

packages/web-component-tester/gulpfile.js
packages/web-component-tester/package.json

Sorry for the churn, but it appears that upgrading to gulp 4 broke some of the tasks used in the release process. This PR should fix that and unblock the #820 release process.
Tested gulp tasks locally and they worked.

Remove run-sequence; fix ordering of gulp tasks

---

packages/modulizer/src/test/unit/project-converter_test.ts

I suspect this behavior changed in #812 and the tests were just not updated. Seems like CI doesn't actually test modulizer anymore since it doesn't have a `test:unit` not `test:integration` script.
Blocking the release of polymer-modulizer@0.4.2 (#820)

Fix modulizer tests to expect PolymerElement

---

packages/gen-typescript-declarations/package-lock.json
packages/gen-typescript-declarations/package.json

Fixes #816 
This PR moves `source-map-support` from dev dependencies to dependencies.
P.S.
I am not sure how the workflow looks like here. Should `--require source-map-support/register` be removed from `packages/gen-typescript-declarations/test/mocha.opts`?

[gen-typescript-declarations] Patching missing dependency for typescript generator

---

packages/bundler/src/bundler.ts

Not sure if this was intentional or I'm just using it wrong but it seems as though paths / dirs specified via the excludes param must be absolute.
The following small change uses the resolved path so that relative paths work.

Use the "resolved" exclude path

---

packages/bundler/CHANGELOG.md
packages/bundler/src/deps-index.ts
packages/bundler/src/html-bundler.ts
packages/bundler/src/test/html-bundler_test.ts

Old logic tried to check Analyzer's assessment of the imported JavaScriptDocument to find out if it was a module, but that assessment is based on the presence of import/export statements instead of the script tag's `type` attribute.
This fix uses the ScriptTagImport instance's `isModule` attribute now, which is consistent regardless of the JavaScriptDocument properties.

Fixed issue #3323 where external module script tag content not inlined

---

packages/bundler/src/bundler.ts

This was just an opportunistic fix after encountering some redundant stuff in bundler's excludes processing code I found after merging in a community PR.

[bundler] Tiny updates to code for removing empty bundles and trim redundant exclude processing code.

---

packages/bundler/CHANGELOG.md
packages/bundler/src/html-bundler.ts
packages/bundler/src/test/cli_test.ts
packages/bundler/src/test/url-utils_test.ts
packages/bundler/src/url-utils.ts
packages/bundler/test/html/bower_components/external-dependency/external-dependency.html
packages/bundler/test/html/url-redirection/home.html

Fixes issue #3329 
Bundler had its own way of rewriting URLs which predated the analyzer's UrlResolver's ability to do so.  By delegating to the analyzer now, we fix an edge case that involved relative URL recalculations for `--redirect` effected URLs with the polymer-bundler CLI.
Changes:
* Fixed issue involving rewriting relative URLs involving crossing `--redirect` boundaries (polymer-bundler CLI feature).
* Removed a couple of exported functions from `url-utils`: `pathPosixRelative` and `rewriteHrefBaseUrl`.

[bundler] Use the analyzer's urlResolver to produce updated relative URLs when rewriting base URLs when inlining html imports.

---

appveyor.yml
packages/bundler/CHANGELOG.md
packages/bundler/src/html-bundler.ts
packages/bundler/src/test/cli_test.ts
packages/bundler/test/html/bower_components/external-dependency/external-dependency.html
packages/bundler/test/html/url-redirection/home.html
packages/bundler/test/html/url-redirection/settings.html

In bundler 3.x if a URL was given (usually in the redirected URL case) like `chrome://` etc the rewriting logic would not convert it to a relative path, but after converting to the analyzer's url resolvers to do the rewriting of URLs this behavior regressed though it was unknown until recently. Added code to ensure URLs containing protocol portion were not rewritten to relative paths in the bundled output.

Updated html-bundler to emit the protocols of URLs when originally given with a protocol (don't relativize them).

---

packages/bundler/CHANGELOG.md
packages/bundler/src/html-bundler.ts
packages/bundler/src/test/html-bundler_test.ts

Preserves the absoluteness of URLs in elements when bundling, where they were all being relativized and that's not fair.

Absolute urls should remain absolute

---

packages/bundler/README.md

I have updated bundle-manifest's url because it is currently pointing to outdated mirror https://github.com/Polymer/polymer-bundler/.

docs: update bundle-manifest's url in Readme

---

packages/build/src/babel-plugin-bare-specifiers.ts

Babel's life cycle appears to make the following combination not possible with the current configuration of polymer's build process.
- `"moduleResolution": "node"`
- `"transformModulesToAmd": true`
- `"bundle": false,`
- Babel processes the tree and transforms `ast` for AMD compilation and/or ES5 syntax in the Program level callback
- This happens PRIOR to processing `babel-plugin-bare-specifiers` `resolveBareSpecifiers` export because it is running in a `CallExpression` which fires later
- The `CallExpression` seeks out things marked 'Import' but because the compiling has already happened, it can't find everything
- Dynamic imports get borked as a result, not being correctly resolved to their actual location in node_modules because it doesn't process it as an Object tree but instead as …

[polymer-build] #3402 resolveBareSpecifiers must be a Program

---

packages/browser-capabilities/CHANGELOG.md
packages/browser-capabilities/src/browser-capabilities.ts

FF 67 (released yesterday) now supports dynamic imports (also confirmed locally):
https://caniuse.com/#search=dynamic%20import
Related: #3403 (but does not fix)

add modules support for FF67 in polyserve

---

packages/cli/src/build/build.ts

Allow JS files to be see as `isInline === false` so that they will skip the minifier.
When working with a Polymer 2 project that includes the Firebase and PolymerFire code, the minification processing delivers those projects with errors. This can be avoided by not minifying those files. With the updates to support Polymer 3, all files were being viewed as `isInline` and as such were not being tested for whether they should or shouldn't be minified. This corrects the code order so that files that are not `isInline` can be seen as such and can be tested for exclusion from the minification pipeline.
Fixes https://github.com/Polymer/tools/issues/279

Allow minify skipping by file glob.

---

.travis.yml

https://github.com/mozilla/geckodriver/issues/1560
The bug linked to above indicates issue with v66+ but v66 is okay for us, v67 broken, so pinning to v66.

Pin Firefox to version 66.0 on Travis because of geckodriver+67.0 bug.

---

package-lock.json
package.json
packages/analyzer/package-lock.json
packages/analyzer/package.json
packages/browser-capabilities/CHANGELOG.md
packages/browser-capabilities/package-lock.json
packages/browser-capabilities/package.json
packages/build/package-lock.json
packages/bundler/package-lock.json
packages/bundler/package.json
packages/bundler/src/test/es6-module-bundling-scenarios_test.ts
packages/cli/package-lock.json
packages/common/package-lock.json
packages/dom5/package-lock.json
packages/editor-service/package-lock.json
packages/editor-service/package.json
packages/esm-amd-loader/package-lock.json
packages/gen-typescript-declarations/package-lock.json
packages/gen-typescript-declarations/package.json
packages/gen-typescript-declarations/src/gen-ts.ts
packages/linter/package-lock.json
packages/modulizer/package-lock.json
packages/polyserve/package-lock.json
packages/project-config/package-lock.json
packages/wct-browser-legacy/package-lock.json
packages/wct-local/package-lock.json
packages/wct-mocha/package-lock.json
packages/wct-sauce/package-lock.json
packages/web-component-tester/package-lock.json
packages/workspaces/package-lock.json

Refreshing the package locks caused a number of breakages, which I also fixed in this PR by pinning some package versions:
- Pinning TypeScript to 3.4 because of new stricter type checking in 3.5, affecting multiple packages
- Pinning to vscode-uri 1.0.6 because the 1.0.7 patch version included a breaking change where scheme-less inputs to `parse` now throw (https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634), affecting multiple packages
- Pinning to Lerna 3.14 because the latest version causes some kind of file-not-found error with bundler on AppVeyor.

Release browser-capabilities 1.1.4

---

packages/wct-local/CHANGELOG.md
packages/wct-local/selenium-overrides.js

Tested this change locally using openjdk@1.13.0 which did not work until this change was introduced and now it works.  By "did not work" I mean that selenium threw a bunch of exceptions and wasn't useable.

Upgrade selenium standalone server to support Java 10+

---

packages/cli/src/commands/serve.ts

Currently when using polyserve with the polymer-cli the --alow-origin switch does not work, this is because --allow-origin is not being added to the serverOptions, i now added it in and tested it and now it's working as it's supposed to.

fixed --allow-origin switch not being added to serverOptions

---

packages/cli/package.json

npm WARN deprecated bower@1.8.2: This Bower version has SECURITY BUG THAT ALLOWS TO WRITE TO ARBITRARY FILE ON YOUR COMPUTER when you install malicious package. Please upgrade Bower to at least version 1.8.8 if you don't want to get hacked. More info: https://snyk.io/blog/severe-security-vulnerability-in-bowers-zip-archive-extraction/

update bower version

---

packages/analyzer/CHANGELOG.md
packages/analyzer/src/javascript/class-scanner.ts
packages/analyzer/src/test/javascript/class-scanner_test.ts
packages/analyzer/src/test/static/class/class-properties.js

Fixes #630.
---
This should handle merging of property information for situations like this:
```js
class Foo {
constructor() {
/** @public some description */
this.someProperty;
}
get someProperty() { return 1; }
}
```
we need to take the description from the constructor but everything else from the actual getter.
in terms of precedence, i take the property's info unless it is empty, then i try take the constructor's info.

analyzer: merge property info from constructors

---

packages/cli/CHANGELOG.md
packages/cli/src/commands/serve.ts

--allow-origin was supported by polyserve, but we never brought that flag into the CLI.  This PR brings that in.  Thanks to @T99rots

Added --allow-origin to the polymer serve command

---

packages/modulizer/README.md

There is a discrepancy between the Readme and the cli help docs regarding the default value of the `--add-import-meta` option.
The help docs state:
```
--add-import-meta               Whether to add a static importMeta property to elements. Defaults to false
```
Referenced value in code: [https://github.com/Polymer/tools/blob/master/packages/modulizer/src/cli/index.ts#L163]()
This also updates the referenced Polymer documentation page, for clarity.

Modulizer: fix readme add-import-meta default value and reference doc URL

---

packages/build/src/html-transform.ts
packages/polyserve/test/bower_components/test-modules/golden/test-suite-wct.html

Fixes https://github.com/Polymer/tools/issues/726
As far as I understand the intention of the injected code it should be safe to assume that all static modules will be loaded by the time the callback is run for the first time. This is why I just disable it for future calls so that dynamic imports do not cause the issues.
I tested this fix on our code containing multiple suites all using components which use dynamic imports. Works well.

Fix injected WCT hack to prevent dynamic modules run Mocha multiple times

---

packages/wct-local/CHANGELOG.md
packages/wct-local/package-lock.json
packages/wct-local/package.json

HTTPS should always be encrypted, while git might not be, and github no longer supports unencrypted git connections. See https://github.blog/2021-09-01-improving-git-protocol-security-github/

Use https instead of git URL
